name: 05 - 1 - event filters and activity types

on:
  push_request:
    types:
      -closed
    branches:
      -main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      -run: echo "running whenever a PR is closed"
