name: 08 - Using Variables

env:
  MY_WORKFLOW_VAR: 'I am a workflow env var'
  OVERWRITTEN: 'I will be overwritten'
  UNDEFINED_VAR_WITH_DEFAULT: ${{ vars.UNDEFINED_VAR || 'default value' }}

on:
  push:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: 'I am a job env var'
      OVERWRITTEN: 'I have been overwritten at the job level'
    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: 'I am a step env var'
          STEP_VAR2: 'I am another step env var'
        run: |
          echo "Step env var: $STEP_VAR"
          echo "Step env var 2: $STEP_VAR2"
          echo "Job env var: $JOB_VAR"
          echo "Workflow env var: $MY_WORKFLOW_VAR"
          echo "Overwritten: $OVERWRITTEN"
      - name: Overwrite job variable
        env:
          OVERWRITTEN: 'I have been overwritten at the step level'
        run: |
          echo "Overwritten (step): $OVERWRITTEN"
echo2:
  runs-on: ubuntu-latest
  steps:
    - name: Print Variables
      run: |
        echo "Org var: ${{ vars.ORG_VAR }}"
        echo "Org overwritten var: ${{ OVERWRITTEN_VAR }}"
        echo "Repo var: ${{ vars.REPOSITORY_VAR }}"
echo-prod:
  runs-on: ubunto-latest
  enviroment: prod
  steps:
    - name: Print Variables
      run: |
        echo "Org var: ${{ vars.ORG_VAR }}"
        echo "Org overwritten var: ${{ OVERWRITTEN_VAR }}"
        echo "Repo var: ${{ vars.REPOSITORY_VAR }}"
        echo "Enviroment var: ${{ vars.TARGET_VAR }}"
echo-undefined:
  runs-on: ubuntu-latest
  steps:
    - name: Print Variables
      run: |
        echo "Org var: ${{ env.UNDEFINED_VAR_WITH_DEFAULT }}"
      

